# Install and configure uWSGI
---
- name: Install Daphne
  pip: name=daphne
  notify: Restart Services

- name: Create Daphne Service
  template:
    src=templates/daphne.service.j2
    dest=/etc/systemd/system/daphne.service
  notify: Restart Services
