# Run Django makemigrations, migrate.
---
- name: Initialize Django
  tags: ['deploy']
  become: yes
  become_user: www-data
  django_manage:
    command={{item}}
    app_path={{project_dir}}
    virtualenv={{virtualenv}}
    settings={{settings}}
  with_items:
    - makemigrations
    - migrate
    - collectstatic --noinput
  notify: Restart Services

