# Run Django makemigrations, migrate.
---
- name: Delete Collectstatic
  tags: ['deploy']
  file:
    state: absent
    path: '{{static_dir}}'

- name: Initialize Django
  tags: ['deploy']
  become: yes
  become_user: www-data
  django_manage:
    command: '{{item}}'
    app_path: '{{project_dir}}'
    virtualenv: '{{virtualenv}}'
    settings: '{{settings}}'
  with_items:
    - makemigrations
    - migrate
    - collectstatic --noinput
  notify: Restart Services

- name: Add Database Backup Cronjob
  cron:
    name: backupdb
    job: '/var/www/venvs/pk/bin/python /root/pk/manage.py backupdb >> {{logs_dir}}/backupdb.log 2>&1'
    minute: '0'
    hour: '0'
    weekday: '0'

- name: Add Update Stocks Cronjob
  cron:
    name: updatestocks
    job: '/var/www/venvs/pk/bin/python /root/pk/manage.py updatestocks >> {{logs_dir}}/updatestocks.log 2>&1'
    minute: '0'
    hour: '2'

- name: Add Update Calendar Cronjob
  cron:
    name: updategcal
    job: '/var/www/venvs/pk/bin/python /root/pk/manage.py updategcal >> {{logs_dir}}/updategcal.log 2>&1'
    minute: '*/5'
