# Install and configure Nginx server.
---
- name: Install Nginx Server
  apt: name=nginx

- name: Remove Nginx default.conf
  file:
    path=/etc/nginx/sites-enabled/default
    state=absent
  notify: Restart Services

- name: Create Nginx {{project_name}}.conf
  template:
    src=templates/nginx.conf.j2
    dest=/etc/nginx/sites-available/{{project_name}}.conf
  notify: Restart Services

- name: Enable Nginx {{project_name}}.conf
  file:
    src=/etc/nginx/sites-available/{{project_name}}.conf
    dest=/etc/nginx/sites-enabled/{{project_name}}.conf
    state=link
  notify: Restart Services
