# Install and configure Redis server.
---
- name: Install Redis Server
  apt: name=redis-server

- name: Configure Redis Server
  lineinfile:
    path: /etc/redis/redis.conf
    regexp: '\#*\s*bind 127.0.0.1'
    line: 'bind 127.0.0.1 ::1'
  notify: Restart Redis
