# _packages.yml
# Install apt and pip packages
---
- name: Create .bash_aliases
  template:
    src=templates/bash_aliases.j2
    dest=~/.bash_aliases

- name: Install Aptitude
  apt: name=aptitude

- name: Update System Packages
  tags: ['update']
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400
  notify: Restart Services

- name: Install System Packages
  apt: name={{item}}
  with_items:
    - git
    - ipython3
    - python3-dev
    - python3-pip
    - sqlite3
    - vim
    - virtualenvwrapper
  notify: Restart Services

- name: Install requirements.pip
  tags: ['update', 'deploy']
  pip: requirements={{requirements}} virtualenv={{virtualenv}}
  notify: Restart Services

- name: Install postactivate Script
  template:
    src=templates/postactivate.j2
    dest={{virtualenv}}/bin/postactivate

- name: Create Log Directory
  file:
    path={{project_dir}}/log
    state=directory
