# Synchronize project files to project_dir
---
- name: Create Project Directory
  file:
    path=/var/www
    state=directory

- name: Sync Project Files
  tags: ['deploy']
  synchronize:
    src: ../pk/
    dest: '{{project_dir}}'
    copy_links: yes
    checksum: yes
    rsync_opts:
      - "--usermap=*:www-data"
      - "--groupmap=*:www-data"
      - '--exclude=*.db'
      - '--exclude=*.sock'
      - '--exclude=*.sqlite3'
      - '--exclude=__pycache__'
      - '--exclude=log'
  notify: Restart Services
