# Install and configure uWSGI
# (c) 2018 M.Shepanski. All rights reserved.
---
- name: Install uWSGI
  pip: name=uwsgi

- name: Create uWSGI Sites Dir
  file:
    path=/etc/uwsgi/sites
    state=directory

- name: Create uWSGI App {{project_name}}-web.ini
  template:
    src=templates/uwsgi-web.ini.j2
    dest=/etc/uwsgi/sites/{{project_name}}-web.ini
  notify: Restart Services

- name: Create uWSGI App {{project_name}}-django.ini
  template:
    src=templates/uwsgi-django.ini.j2
    dest=/etc/uwsgi/sites/{{project_name}}-django.ini
  notify: Restart Services

- name: Create uWSGI Service
  template:
    src=templates/uwsgi.service.j2
    dest=/etc/systemd/system/uwsgi.service
  notify: Restart Services
