# _django.yml
# Run Django makemigrations, migrate, collectstatic
---
- name: Initialize Django
  tags: ['deploy']
  django_manage:
    command={{item}}
    app_path={{project_dir}}
    virtualenv={{virtualenv}}
    settings={{settings}}
  with_items:
    - makemigrations
    - migrate
  notify: Restart Services
