# _packages.yml
# Install apt and pip packages
---
- name: Installing .bash_aliases
  template:
    src=conf/bash_aliases.j2
    dest=~/.bash_aliases

- name: Installing Aptitude
  apt: name=aptitude

- name: Updating System Packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: Installing System Packages
  apt: name={{item}}
  with_items:
    - git
    - ipython3
    - python3-dev
    - python3-pip
    - sqlite3
    - vim
    - virtualenvwrapper

- name: Installing requirements.pip
  pip: requirements={{requirements}} virtualenv={{virtualenv}}

- name: Creating Log Directory
  file:
    path={{project_dir}}/log
    state=directory
