# Main Ansible Playbook File
#
# Example Usage:
#  > ansible-playbook -i inventory.ini playbook.yml
#  > ansible-playbook -i inventory.ini playbook.yml --tags=deploy
---
- hosts: web
  remote_user: root
  become: yes
  become_method: sudo
  vars_files:
    - vars/main.yml

  tasks:

  handlers:
    - name: Restart Redis
      service: name=redis state=restarted

    - name: Restart Services
      service: name={{item}} state=restarted
      with_items:
        - nginx
        - uwsgi
