# playbook.yml
# Main Ansible Playbook File
#
# Example Usage:
#  > ansible-playbook -i inventory.ini playbook.yml
#  > ansible-playbook -i inventory.ini playbook.yml --tags=deploy
# 
# _secrets.yml not checked in; contains: email
---
- hosts: web
  remote_user: root
  become: yes
  become_method: sudo
  vars_files:
    - vars/main.yml
    - vars/secrets.yml

  tasks:
    - include_tasks: tasks/upload.yml
    - include_tasks: tasks/system.yml
    - include_tasks: tasks/django.yml
    - include_tasks: tasks/certbot.yml
    - include_tasks: tasks/redis.yml
    - include_tasks: tasks/nginx.yml
    - include_tasks: tasks/uwsgi.yml

  handlers:
    - name: Restart Services
      service: name={{item}} state=restarted
      with_items:
        - redis
        - nginx
        - uwsgi

