# playbook.yml
# Main Ansible Playbook File
#
# Example Usage:
#  > ansible-playbook -i inventory.ini playbook.yml
#  > ansible-playbook -i inventory.ini playbook.yml --tags=deploy
# 
# _secrets.yml not checked in; contains: email
---
- hosts: web
  remote_user: root
  become: yes
  become_method: sudo
  vars_files:
    - _secrets.yml
    - _vars.yml

  tasks:
    - include_tasks: _upload.yml
    - include_tasks: _system.yml
    - include_tasks: _django.yml
    - include_tasks: _certbot.yml
    - include_tasks: _redis.yml
    - include_tasks: _nginx.yml
    - include_tasks: _uwsgi.yml

  handlers:
    - name: Restart Services
      service: name={{item}} state=restarted
      with_items:
        - redis
        - nginx
        - uwsgi

